### ISSUE TITLE
Push client-side packages to npm

### ISSUE THREAD

**Issue by pkozlowski-opensource** [caridy/es6-micro-loader#3]
I was wondering if it would be possible to have https://github.com/caridy/es6-micro-loader/tree/master/dist as part of the package pushed to npm? This would help people who use npm for client-side packages as well.

**Comment by caridy** [comment]
fixed in https://github.com/caridy/es6-micro-loader/commit/f25b6e98a1f8a2dc16f8b31fb72d830c2a747703

**Comment by caridy** [comment]
- es6-micro-loader@0.2.1

**Comment by pkozlowski-opensource** [comment]
Wow, this was fast! Thank you @caridy !
